FROM alpine:3.21 AS build
RUN apk update && \
    apk add --update alpine-sdk
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN mkdir bin
# Compile statically so runtime has no dependencies
RUN gcc -static -O2 hello.c -o bin/hello

FROM scratch
COPY --from=build /app/bin/hello /app/hello
ENTRYPOINT ["/app/hello"]